import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import StoreProvider from "./StoreProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DersiGo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          <ToastContainer />
          <main className="container mx-auto p-4">{children}</main>
        </body>
      </html>
    </StoreProvider>
  );
}
