export const inputTypes = [
  {
    type: "text",
    name: "firstName",
    id: "firstName",
    placeholder: "First Name",
    label: "First Name",
    col: 2,
    required: true,
  },
  {
    type: "text",
    name: "lastName",
    id: "lastName",
    placeholder: "Last Name",
    label: "Last Name",
    col: 2,
    required: true,
  },
  {
    type: "email",
    name: "email",
    id: "email",
    placeholder: "E-mail",
    label: "E-mail",
    col: 2,
    required: true,
  },
  {
    type: "text",
    name: "phone",
    id: "phone",
    placeholder: "Phone Number",
    label: "Phone",
    col: 2,
    required: false,
  },
  {
    type: "select",
    name: "gender",
    id: "gender",
    placeholder: "Gender",
    label: "Gender",
    col: 2,
    options: ["", "Male", "Female", "Other"],
    required: false,
  },
  {
    type: "select",
    name: "title",
    id: "title",
    placeholder: "Title",
    label: "Title",
    col: 2,
    options: ["", "Mr", "Ms", "Mrs", "Miss", "Dr"],
    required: false,
  },
  {
    type: "text",
    name: "picture",
    id: "picture",
    placeholder: "Picture Url",
    label: "Picture",
    col: 1,
    required: false,
  },
];
